animales x = if x == "perro"
                      then "guau"
                      else if x == "gato"
		      then "miau"
		      else if x == "cerdo"
		      then "oink"
                      else if x == "gallina"
		      then "cococo"
                      else if x == "pollito"
		      then "piopio"
                      else if x == "gallo"
		      then "quiquiriqui"
                      else if x == "pavo"
		      then "gluglu"
                      else if x == "oveja"
		      then "bee"
                      else if x == "pato"
		      then "cuack"
                      else if x == "rana"
		      then "croac"
                      else if x == "vaca"
		      then "muu"
                      else if x == "vibora"
		      then "ssss"
                      else if x == "grillo"
		      then "cricricri"
                      else if x == "leon"
		      then "grrr"
                      else if x == "buho"
		      then "huuhuu"
		      else "Al parecer no pusiste un animal, recarga e intentalo de nuevo"

                      